# Generated by Django 5.1.4 on 2025-10-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('companies', '0005_limitedsubmissiondeadlinetracker_assigned_to'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaxableIncomeSourceForSubmission',
            new_name='TaxableIncomeSourceForSubmissionPerTaxYear',
        ),
        migrations.RemoveConstraint(
            model_name='selfemploymentdeductionspertaxyear',
            name='unique deduction record',
        ),
        migrations.RemoveConstraint(
            model_name='selfemploymentexpensespertaxyear',
            name='unique expense record',
        ),
        migrations.RemoveConstraint(
            model_name='selfemploymentincomespertaxyear',
            name='unique record',
        ),
        migrations.AddConstraint(
            model_name='selfemploymentdeductionspertaxyear',
            constraint=models.UniqueConstraint(fields=('client', 'deduction_source'), name='unique_SelfemploymentDeductionsPerTaxYear'),
        ),
        migrations.AddConstraint(
            model_name='selfemploymentexpensespertaxyear',
            constraint=models.UniqueConstraint(fields=('client', 'month', 'expense_source'), name='unique_SelfemploymentExpensesPerTaxYear'),
        ),
        migrations.AddConstraint(
            model_name='selfemploymentincomespertaxyear',
            constraint=models.UniqueConstraint(fields=('client', 'month', 'income_source'), name='unique_SelfemploymentIncomesPerTaxYear'),
        ),
        migrations.AddConstraint(
            model_name='taxableincomesourceforsubmissionpertaxyear',
            constraint=models.UniqueConstraint(fields=('submission', 'taxable_income_source'), name='unique_TaxableIncomeSourceForSubmissionPerTaxYear'),
        ),
    ]
