# Generated by Django 5.1.4 on 2025-06-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_limited_nino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedsubmissiondeadlinetracker',
            name='payment_status',
            field=models.CharField(blank=True, choices=[(None, '--------------'), ('NOT PAID', 'NOT PAID'), ('INVOICE SENT', 'INVOICE SENT'), ('PARTIALLY PAID', 'PARTIALLY PAID'), ('PAID', 'PAID')], default=None, max_length=55, null=True, verbose_name='Payment Status'),
        ),
    ]
