# Generated by Django 5.1.4 on 2025-06-04 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_limitedsubmissiondeadlinetracker_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='limitedsubmissiondeadlinetracker',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='limited_submission_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to'),
        ),
    ]
