# Generated by Django 5.1.4 on 2025-10-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_limitedsubmissiondeadlinetracker_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedsubmissiondeadlinetracker',
            name='status',
            field=models.CharField(blank=True, choices=[(None, '--------------'), ('DOCUMENT REQUESTED', 'DOCUMENT REQUESTED'), ('WAITING FOR INFORMATION', 'WAITING FOR INFORMATION'), ('DOCUMENT RECEIVED', 'DOCUMENT RECEIVED'), ('PROCESSING', 'PROCESSING'), ('READY FOR SUBMISSION', 'READY FOR SUBMISSION'), ('WAITING FOR CONFIRMATION', 'WAITING FOR CONFIRMATION'), ('COMPLETED', 'COMPLETED'), ('EXTENDED', 'EXTENDED')], default=None, max_length=55, null=True, verbose_name='Status'),
        ),
    ]
