# Generated by Django 5.1.4 on 2025-11-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_limitedsubmissiondeadlinetracker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='limited',
            name='CH_personal_codes',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='CH Personal Codes'),
        ),
    ]
