# Generated by Django 5.1.4 on 2025-11-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_limited_ch_personal_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limited',
            name='gateway_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Gateway ID'),
        ),
    ]
