# Generated by Django 5.2.8 on 2026-01-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_limited_gateway_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfassesmentaccountsubmission',
            name='payment_date',
            field=models.DateField(default=None, null=True, verbose_name='Payment Date'),
        ),
    ]
