# Generated by Django 5.2.8 on 2026-01-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_limited_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitedsubmissiondeadlinetracker',
            name='planning_date',
            field=models.DateField(null=True, verbose_name='Planning date'),
        ),
    ]
