# Generated by Django 5.2.8 on 2026-01-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_limitedsubmissiondeadlinetracker_planning_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedsubmissiondeadlinetracker',
            name='planning_date',
            field=models.DateField(blank=True, null=True, verbose_name='Planning date'),
        ),
    ]
