# Generated by Django 5.2.8 on 2026-05-31 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_alter_limitedsubmissiondeadlinetracker_planning_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='limitedsubmissiondeadlinetracker',
            options={'ordering': ['-planning_date', '-HMRC_deadline', '-our_deadline'], 'verbose_name': 'Limited Submission', 'verbose_name_plural': 'Limited Submissions'},
        ),
    ]
